backend:
  name: git-gateway
  branch: netlifycms
media_folder: public/uploads
public_folder: uploads
collections:
  - label: "Blog"
    name: "blog"
    folder: "blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Meta Title", name: "metaTitle", widget: "string"}
      - {label: "Meta Description", name: "metaDescription", widget: "string"}
      - {label: "Meta Image", name: "metaImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: 'Tags'
        name: "tags"
        widget: list
  - name: "settings"
    label: "Settings"
    extension: "json"
    editor:
      preview: false

    files:
      - file: "content/seo.json"
        label: "Search Engine Optimization"
        name: "seo"

        fields:
          - { name: title, label: Title, widget: string }
          - { name: description, label: Description, widget: string }
          - { name: "image", label: "Image", widget: "image" }