name: Deploy push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - none
  repository_dispatch:

env:
  NEXT_PUBLIC_URL: ${{secrets.NEXT_PUBLIC_URL}}
  GOOGLE_ANALYTICS_KEY: ${{secrets.GOOGLE_ANALYTICS_KEY}}
  NEXT_PUBLIC_TINY_API_KEY: ${{secrets.NEXT_PUBLIC_TINY_API_KEY}}
  
jobs:
  start:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          node_modules-${{ hashFiles('**/yarn.lock') }}
          node_modules-

    - name: Cache NextJS
      uses: actions/cache@v2
      with:
        path: .next/cache
        key: nextjs-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          nextjs-${{ hashFiles('**/yarn.lock') }}
          nextjs-

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        cache-key: cypress-${{ hashFiles('**/yarn.lock') }}
        build: yarn export
        start: yarn start

      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: out